package fiuba.algo3.algocraft;

public enum TipoDeConstruccion {
    ADICIONAL_SUMINISTROS, EXTRACTOR_GAS, EXTRACTOR_MINERAL, CREADOR_DE_UNIDADES_BASICAS, CREADOR_DE_UNIDADES_AVANZADAS, CREADOR_DE_UNIDADES_MAGICAS
}
