package fiuba.algo3.algocraft;

public enum TipoDeConstruccion {
    ADICIONAL_SUMINISTROS, EXTRACTOR_GAS, EXTRACTOR_MINERAL, CREADOR_DE_SOLDADOS, CREADOR_DE_UNIDADES_TERRESTRES, CREADOR_DE_UNIDADES_AEREAS
}
